/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SChild {
    }
    interface SNoshadowBorder {
    }
    interface SShadowBorder {
    }
}
declare global {
    interface HTMLSChildElement extends Components.SChild, HTMLStencilElement {
    }
    var HTMLSChildElement: {
        prototype: HTMLSChildElement;
        new (): HTMLSChildElement;
    };
    interface HTMLSNoshadowBorderElement extends Components.SNoshadowBorder, HTMLStencilElement {
    }
    var HTMLSNoshadowBorderElement: {
        prototype: HTMLSNoshadowBorderElement;
        new (): HTMLSNoshadowBorderElement;
    };
    interface HTMLSShadowBorderElement extends Components.SShadowBorder, HTMLStencilElement {
    }
    var HTMLSShadowBorderElement: {
        prototype: HTMLSShadowBorderElement;
        new (): HTMLSShadowBorderElement;
    };
    interface HTMLElementTagNameMap {
        "s-child": HTMLSChildElement;
        "s-noshadow-border": HTMLSNoshadowBorderElement;
        "s-shadow-border": HTMLSShadowBorderElement;
    }
}
declare namespace LocalJSX {
    interface SChild {
    }
    interface SNoshadowBorder {
    }
    interface SShadowBorder {
    }
    interface IntrinsicElements {
        "s-child": SChild;
        "s-noshadow-border": SNoshadowBorder;
        "s-shadow-border": SShadowBorder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s-child": LocalJSX.SChild & JSXBase.HTMLAttributes<HTMLSChildElement>;
            "s-noshadow-border": LocalJSX.SNoshadowBorder & JSXBase.HTMLAttributes<HTMLSNoshadowBorderElement>;
            "s-shadow-border": LocalJSX.SShadowBorder & JSXBase.HTMLAttributes<HTMLSShadowBorderElement>;
        }
    }
}
